exec:
  max_threads: 2
  min_output_tasks: 1
in:
  type: file
  path_prefix: C:\Users\AnkitKumar\Desktop\embulk-filter-mysqllookup\calendar.csv
  parser:
    type: csv
    columns:
      - { name: dim_calendar_key, type: long }
      - { name: year_number, type: long }
      - { name: quarter_number, type: long }
      - { name: attr_1, type: string }
filters:
  - type: mysql_lookup
    host: localhost
    port: 3306
    driver_path: C:/Users/AnkitKumar/Desktop/embulk-plugins/mysql-connector-java-8.0.19.jar
    driver_class: com.mysql.cj.jdbc.Driver
    database: information
    table_name: country
    username: root
    password: root
    mapping_from:
      - quarter_number
      - attr_1
    mapping_to:
      - id
      - country_code
    new_columns:
      - { name: country_address, type: string }
      - { name: country_code,type: double}
out:
  type: file
  path_prefix: C:/Users/AnkitKumar/Desktop/embulk-files/sample/output.csv
  file_ext: csv
  formatter:
      type: csv
      delimiter: "\t"
      newline: CRLF
      newline_in_field: LF
      charset: UTF-8
      quote_policy: MINIMAL
      quote: '"'
      escape: "\\"
      null_string: "\\N"
      default_timezone: 'UTC'