exec:
  max_threads: 2
  min_output_tasks: 1
in:
  type: mysql
  host: localhost
  port: 3306
  user: root
  password: root
  database: information
  query: |
    SELECT * from table1;
filters:
  - type: mysql_lookup
    host: localhost
    port: 3306
    database: information
    table_name: countryinfo
    username: root
    password: root
    mapping_from:
      - id
      - country_address
    mapping_to:
      - country_id
      - country_address
    new_columns:
      - { name: country_population, type: string }
      - { name: country_gdp,type: string}
out:
  type: file
  path_prefix: /home/ankit/info-projects/output.csv
  file_ext: csv
  formatter:
    type: csv
    delimiter: "\t"
    newline: CRLF
    newline_in_field: LF
    charset: UTF-8
    quote_policy: MINIMAL
    quote: '"'
    escape: "\\"
    null_string: "\\N"
    default_timezone: 'UTC'
